"""
Django settings for adietalkradio_admin project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import environ
import os

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost', '187.124.218.83', 'adietalkradio.com', '.adietalkradio.com'])


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'cloudinary_storage',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django.contrib.sites',
    
    # Local apps
    'radio',
]

SITE_ID = 1

# Frontend URL used in password reset emails (pointing to your Flutter app deep link)
FRONTEND_URL = 'adietalkafrica://reset-password'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'adietalkradio_admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'adietalkradio_admin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'static_root'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media Files Settings
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary Storage Settings
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': env('CLOUDINARY_API_KEY'),
    'API_SECRET': env('CLOUDINARY_API_SECRET')
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# ---  Email Settings (Gmail SMTP) ---
# To enable emails:
# 1. Go to myaccount.google.com/apppasswords
# 2. Generate an App Password for "Mail"
# 3. Paste your Gmail and the App Password below
EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = env('EMAIL_HOST')
EMAIL_PORT          = env.int('EMAIL_PORT')
EMAIL_USE_TLS       = env.bool('EMAIL_USE_TLS', default=False)
EMAIL_USE_SSL       = env.bool('EMAIL_USE_SSL', default=True)
EMAIL_HOST_USER     = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL  = env('DEFAULT_FROM_EMAIL')
MARKETING_ADMIN_EMAIL = env('MARKETING_ADMIN_EMAIL')

# Django REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFY_SIGNING_KEY': True,
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS Settings (Allow apps to connect)
# CORS Settings
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://187.124.218.83",
])
CORS_ALLOW_CREDENTIALS = True

from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Unfold settings for Admin UI Customization (Tailwind CSS based)
UNFOLD = {
    "SITE_TITLE": _("AdieTalkRadio Admin"),
    "SITE_HEADER": _("AdieTalkRadio"),
    "SITE_URL": "/",
    "SITE_ICON": lambda request: STATIC_URL + "images/logo.png",
    "SITE_LOGO": lambda request: STATIC_URL + "images/logo.png",
    "SITE_SYMBOL": "radio",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "DASHBOARD_CALLBACK": "radio.utils.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "254 242 242",
            "100": "254 226 226",
            "200": "254 202 202",
            "300": "252 165 165",
            "400": "248 113 113",
            "500": "192 57 43",  # #C0392B (Primary Red)
            "600": "153 27 27",
            "700": "127 29 29",
            "800": "153 27 27",
            "900": "127 29 29",
            "950": "127 29 29",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Navigation"),
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                ],
            },
            {
                "title": _("Radio Management"),
                "items": [
                    {
                        "title": _("Live Stream"),
                        "icon": "sensors",
                        "link": reverse_lazy("admin:radio_livestream_changelist"),
                    },
                    {
                        "title": _("Shows & Schedule"),
                        "icon": "calendar_month",
                        "link": reverse_lazy("admin:radio_show_changelist"),
                    },
                    {
                        "title": _("Podcasts"),
                        "icon": "mic",
                        "link": reverse_lazy("admin:radio_podcast_changelist"),
                    },
                    {
                        "title": _("News Articles"),
                        "icon": "article",
                        "link": reverse_lazy("admin:radio_newsarticle_changelist"),
                    },
                    {
                        "title": _("Team Members"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:radio_teammember_changelist"),
                    },
                ],
            },
            {
                "title": _("Marketing & Registration"),
                "items": [
                    {
                        "title": _("Webinar Events"),
                        "icon": "event",
                        "link": reverse_lazy("admin:radio_webinarevent_changelist"),
                    },
                    {
                        "title": _("Registrations"),
                        "icon": "how_to_reg",
                        "link": reverse_lazy("admin:radio_webinarregistration_changelist"),
                    },
                    {
                        "title": _("Promotions"),
                        "icon": "campaign",
                        "link": reverse_lazy("admin:radio_promotion_changelist"),
                    },
                    {
                        "title": _("Banners"),
                        "icon": "image",
                        "link": reverse_lazy("admin:radio_banner_changelist"),
                    },
                ],
            },
        ],
    },
    "STYLES": [
        lambda request: STATIC_URL + "css/unfold_custom.css",
    ],
}

# Where to redirect users after successful login
LOGIN_REDIRECT_URL = '/admin/'

