# Generated by Django 4.2.29 on 2026-03-09 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_contactmessage_promotionpayment_webinarregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(choices=[('music_airplay', 'Music Airplay'), ('interview_booking', 'Interview Booking')], max_length=50)),
                ('artist_name', models.CharField(blank=True, max_length=150, null=True)),
                ('song_title', models.CharField(blank=True, max_length=150, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('song_link', models.URLField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('preferred_date', models.DateTimeField()),
                ('topic', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='team/')),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=150, unique=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='radio.promotion')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='PromotionPayment',
        ),
        migrations.RenameField(
            model_name='webinarregistration',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='webinarregistration',
            old_name='company',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='webinarregistration',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='webinarregistration',
            name='job_title',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(default='News', max_length=100),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category_color',
            field=models.CharField(default='#FF0000', max_length=20),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='podcast',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='podcast',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='presenter',
            name='role',
            field=models.CharField(default='OAP', max_length=100),
        ),
        migrations.AddField(
            model_name='show',
            name='show_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
