# Generated by Django 4.2.29 on 2026-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_promotion_teammember_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarregistration',
            name='interested',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
