# Generated by Django 4.2.29 on 2026-03-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_webinarregistration_interested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinarregistration',
            old_name='created_at',
            new_name='registered_at',
        ),
        migrations.RemoveField(
            model_name='webinarregistration',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='webinarregistration',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='webinarregistration',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webinarregistration',
            name='phone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webinarregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='webinarregistration',
            name='interested',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webinarregistration',
            name='organization',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
