# Generated by Django 4.2.29 on 2026-03-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_rename_created_at_webinarregistration_registered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Adietalk Webinar', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.CharField(help_text='e.g., Saturday, February 22, 2026', max_length=150)),
                ('time', models.CharField(help_text='e.g., 11AM (EST) & 5PM (WAT)', max_length=150)),
                ('platform', models.CharField(default='Zoom', max_length=100)),
                ('link', models.URLField(max_length=500)),
                ('meeting_id', models.CharField(blank=True, max_length=100, null=True)),
                ('passcode', models.CharField(blank=True, max_length=100, null=True)),
                ('flyer_image', models.ImageField(blank=True, null=True, upload_to='webinars/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one webinar should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webinar Event',
                'verbose_name_plural': 'Webinar Events',
            },
        ),
    ]
