# Generated by Django 4.2.29 on 2026-03-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_webinarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarevent',
            name='date',
            field=models.DateField(help_text='Select the date of the webinar'),
        ),
        migrations.AlterField(
            model_name='webinarevent',
            name='time',
            field=models.TimeField(help_text='Select the start time of the webinar'),
        ),
    ]
