# Generated by Django 4.2.29 on 2026-03-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_alter_webinarevent_date_alter_webinarevent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarevent',
            name='date',
            field=models.CharField(help_text='e.g., Saturday, February 22, 2026', max_length=150),
        ),
        migrations.AlterField(
            model_name='webinarevent',
            name='time',
            field=models.CharField(help_text='e.g., 11AM (EST) & 5PM (WAT)', max_length=150),
        ),
    ]
