# Generated by Django 4.2.29 on 2026-03-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0009_remove_newsarticle_likes_newsarticle_liked_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='show',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='show',
            name='days',
            field=models.ManyToManyField(related_name='shows', to='radio.day'),
        ),
    ]
