# Generated by Django 4.2.29 on 2026-03-14 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0011_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='presenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='radio.teammember'),
        ),
        migrations.DeleteModel(
            name='Presenter',
        ),
    ]
