# Generated by Django 4.2.29 on 2026-03-14 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radio', '0012_alter_show_presenter_delete_presenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_podcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcast',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
