# Generated by Django 4.2.29 on 2026-03-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0013_podcast_liked_by_podcast_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('notify_type', models.CharField(blank=True, help_text="e.g. 'news', 'podcast', 'show'", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
