# Generated by Django 4.2.29 on 2026-03-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0014_broadcastnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotification',
            name='content_id',
            field=models.CharField(blank=True, help_text='ID of the related object (News, Podcast, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broadcastnotification',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
