# Generated by Django 4.2.29 on 2026-04-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0015_broadcastnotification_content_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='budget_estimation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='campaign_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='preferred_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(choices=[('music_airplay', 'Music Airplay'), ('interview_booking', 'Interview Booking'), ('advertisement', 'Advertisement & Sponsorships')], max_length=50),
        ),
    ]
