# Generated by Django 4.2.29 on 2026-04-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0016_promotion_budget_estimation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='advertisement_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='social_media',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
