# Generated by Django 4.2.29 on 2026-04-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0017_promotion_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
