# Generated by Django 4.2.29 on 2026-04-24 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0018_alter_promotion_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], max_length=50, unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Analytics',
                'verbose_name_plural': 'Platform Analytics',
            },
        ),
        migrations.CreateModel(
            name='ArchiveShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_aired', models.DateField()),
                ('audio_file', models.FileField(blank=True, help_text='Upload MP3 file of the previous show', null=True, upload_to='archive_shows/audio/')),
                ('audio_url', models.URLField(blank=True, help_text='Or provide external audio URL', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='archive_shows/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('presenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_shows', to='radio.teammember')),
            ],
            options={
                'verbose_name': 'Archived Show',
                'verbose_name_plural': 'Archived Shows',
                'ordering': ['-date_aired'],
            },
        ),
    ]
