# Generated by Django 4.2.29 on 2026-05-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0020_teammember_facebook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarregistration',
            name='webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='radio.webinarevent'),
        ),
        migrations.AlterField(
            model_name='webinarregistration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='webinarregistration',
            unique_together={('email', 'webinar')},
        ),
    ]
